export const products = [
  {
    description: 'krabby patty',
    itemId: '123',
    casePack: '1x3',
    caseWeight: '12lb',
    price: 150,
  },
  {
    description: 'chum bucket',
    itemId: '124',
    casePack: '1x3',
    caseWeight: '12lb',
    price: 75,
  },
  {
    description: 'fries',
    itemId: '125',
    casePack: '1x3',
    caseWeight: '12lb',
    price: 25,
  },
  {
    description: 'krabby patty1',
    itemId: '126',
    casePack: '1x3',
    caseWeight: '12lb',
    price: 150,
  },
  {
    description: 'chum bucket1',
    itemId: '127',
    casePack: '1x3',
    caseWeight: '12lb',
    price: 75,
  },
  {
    description: 'fries1',
    itemId: '128',
    casePack: '1x3',
    caseWeight: '12lb',
    price: 25,
  },
  {
    description: 'krabby patty2',
    itemId: '129',
    casePack: '1x3',
    caseWeight: '12lb',
    price: 150,
  },
  {
    description: 'chum bucket2',
    itemId: '130',
    casePack: '1x3',
    caseWeight: '12lb',
    price: 75,
  },
  {
    description: 'fries2',
    itemId: '131',
    casePack: '1x3',
    caseWeight: '12lb',
    price: 25,
  },
];
